[package]
name = "dns-parser"
description = """
    Pure-rust DNS protocol parser library. This does not support network, only
    raw protocol parser.
"""
license = "MIT"
readme = "README.rst"
keywords = ["dns", "domain", "name", "parser"]
homepage = "http://github.com/tailhook/dns-parser"
version = "0.1.0"
authors = ["paul@colomiets.name"]

[dependencies]
quick-error = "0.2.1"
nom = "1.1"
ip = "1.0"

[dev-dependencies]

[lib]
name = "dns_parser"
path = "src/lib.rs"

